import 'package:madezone_study_student_app/model/penalty_reason.dart';
import 'package:madezone_study_student_app/model/penalty_category.dart';

final List<PenaltyReason> samplePenaltyReasons = [
  PenaltyReason(
    id: '1',
    category: PenaltyCategory.tardy,
    penaltyId: 'P001',
    startDate: DateTime.now().subtract(Duration(days: 5)),
    endDate: DateTime.now().subtract(Duration(days: 4)),
    description: '오전 수업 지각',
    imageUrl: null,
  ),
  PenaltyReason(
    id: '2',
    category: PenaltyCategory.learningAttitude,
    penaltyId: 'P002',
    startDate: DateTime.now().subtract(Duration(days: 3)),
    endDate: DateTime.now().subtract(Duration(days: 2)),
    description: '수학 과제 미제출',
    imageUrl: 'https://picsum.photos/80',
  ),
  PenaltyReason(
    id: '3',
    category: PenaltyCategory.learningAttitude,
    penaltyId: 'P003',
    startDate: DateTime.now().subtract(Duration(days: 2)),
    endDate: DateTime.now().subtract(Duration(days: 1)),
    description: '수업 중 휴대폰 사용',
    imageUrl: null,
  ),
  PenaltyReason(
    id: '4',
    category: PenaltyCategory.tardy,
    penaltyId: 'P004',
    startDate: DateTime.now().subtract(Duration(days: 1)),
    endDate: DateTime.now(),
    description: '오후 수업 지각',
    imageUrl: null,
  ),
  PenaltyReason(
    id: '5',
    category: PenaltyCategory.learningAttitude,
    penaltyId: 'P005',
    startDate: DateTime.now(),
    endDate: DateTime.now().add(Duration(days: 1)),
    description: '영어 과제 미제출',
    imageUrl: 'https://picsum.photos/80',
  ),
  PenaltyReason(
    id: '6',
    category: PenaltyCategory.learningAttitude,
    penaltyId: 'P006',
    startDate: DateTime.now().add(Duration(days: 1)),
    endDate: DateTime.now().add(Duration(days: 2)),
    description: '친구와 잡담',
    imageUrl: null,
  ),
  PenaltyReason(
    id: '7',
    category: PenaltyCategory.tardy,
    penaltyId: 'P007',
    startDate: DateTime.now().add(Duration(days: 2)),
    endDate: DateTime.now().add(Duration(days: 3)),
    description: '아침 자습 지각',
    imageUrl: null,
  ),
  PenaltyReason(
    id: '8',
    category: PenaltyCategory.learningAttitude,
    penaltyId: 'P008',
    startDate: DateTime.now().add(Duration(days: 3)),
    endDate: DateTime.now().add(Duration(days: 4)),
    description: '과학 실험 보고서 미제출',
    imageUrl: 'https://picsum.photos/80',
  ),
  PenaltyReason(
    id: '9',
    category: PenaltyCategory.learningAttitude,
    penaltyId: 'P009',
    startDate: DateTime.now().add(Duration(days: 4)),
    endDate: DateTime.now().add(Duration(days: 5)),
    description: '수업 중 취침',
    imageUrl: null,
  ),
  PenaltyReason(
    id: '10',
    category: PenaltyCategory.learningAttitude,
    penaltyId: 'P010',
    startDate: DateTime.now().add(Duration(days: 5)),
    endDate: DateTime.now().add(Duration(days: 6)),
    description: '교칙 위반',
    imageUrl: null,
  ),
];
